open Format

let pp_dashbaord (fmt : Format.formatter) (todos : Todo.t list) =
  Format.pp_set_margin fmt 100_000;
  fprintf fmt "@.## Tech Debt Dashbaord";
  fprintf fmt
    {|@.
> Tech dept is the mind-killer. MuadʾDebt combs your code for TODOs.  
> You must face your dept; resolve it and let it pass.  
> Where the debt has gone, only flow remains.@.|};

  let open Todo in
  let most_urgent_first_todos =
    List.stable_sort (fun t1 t2 -> Int.compare t1.urgency t2.urgency) todos
  in
  List.iter
    (fun t ->
      let loc = t.location in
      fprintf fmt "@. - [%s(%d): %s](%s#%d)"
        (Marker.to_string t.marker)
        t.urgency t.msg loc.file loc.line)
    most_urgent_first_todos;

  fprintf fmt
    "@.@.  ~~ generated by [MuadʾDebt](https://github.com/cz4rny/muaddept) 🐫"
